### ISSUE TITLE
Vote: how should we write this project's name

### ISSUE THREAD

**Issue by lexelby** [lexelby/inkstitch#116]
My original thought with the name of this project is that it should be written as "ink/stitch" -- lower case and including the slash.  The slash was kind of an ironic/tongue-in-cheek nod to all the hipster names that are floating around the internet.  I also wanted to specifically indicate that it's a mash-up of Inkscape and embroidery to make a combined tool.

I'd like to know what you folks think.  Is the slash stupid?  How do you like to write it?  Here are all of the spellings of "ink/stitch" that I can think of:

* ink/stitch
* Ink/stitch
* Ink/Stitch
* inkstitch
* Inkstitch
* InkStitch
* inkStitch
* ink stitch
* Ink Stitch
* ink-stitch
* Ink-Stitch

Which do you prefer?  Let's vote. Just write your choice in a comment and we'll see which one is the most popular.

cc @wwderw @AkiraNorthstar @X3msnake

**Comment by X3msnake** [comment]
inkStitch

**Comment by wwderw** [comment]
I personally do like the slash, I'm more of the Ink/Stitch variety though.

**Comment by lexelby** [comment]
I should note, I'm definitely not wedded to the lower-case thing.

**Comment by AkiraNorthstar** [comment]
As long as ink/stitch is not used as a directory name, I think the following varieties are fine:
- ink/stitch
- Ink/stitch
- Ink/Stitch

I don't like escape sequences in directory names... ;-)

**Comment by X3msnake** [comment]
Here's a illustration why i think slash pipe and other characters are a bad bet :(

![image](https://user-images.githubusercontent.com/11083514/36978739-3ef2c112-207d-11e8-972c-5b1cd7ffecfb.png)

**Comment by wwderw** [comment]
In branding, there are always different ways to doing something for different applications.

As long as it doesn't affect the overall optics of the brand itself, having something that shows up on swag (for just an example) can be different (to a degree) then how it shows up in computer files/folders.

**Comment by X3msnake** [comment]
True, but if you can have both respect the brand it is better, that's why i voted for inkStitch.

you get the same separation between ink and Stitch without the technical issues. but that's just me i like to have things propagate trough all media with the same identity when possible. ;)

**Comment by lexelby** [comment]
As you're saying, @wwderw, I'm talking about the branding, and _not_ the way we'd write it for file names, module names in the code, etc.  I don't care about those, "inkstitch" is fine.

**Comment by thewildotter** [comment]
**ink---stitch**

How about ink---stitch ?  Minus symbols are fine in filenames without escapes.  The three minus signs is artsy.  It connects (with stitching) ink and stitching.   There is no case twiddling.  It makes distinguishing between inkscape and inkstitch at a glance very easy.   Finding files with three consecutive minus symbols is very easy using grep or find or perl re's or ...  
Yes, I am a Johnny---come---lately, complete noobie, in this community.  I have a Brother PE-770 on which I have ambitions to do **Moire patterns**(ie. using x-y offset spirals or rulings) and perhaps even kinetic Moire(x-y-z) on sheer fabric(eg. organza  or maybe even FSL) with significant space between layers.  I have generated a few first drawings with Satin Columns but I must have made a mistake when installing 1.3.1 because my emboider settings only allows melco, csv, pcode  and no machine specific output filetype settings(I want .pes).  I will purge my inkscape from my Ubuntu 16.04 and reinstall everything to see if I can get the other options to show up.  I had multiple earlier installs of  inkstitch 1.0 in both the user and system extensions and I think that chaff is boogering up my inkstitch.  Is there already some way of getting an "about" for the inkstitch extension version currently in use at execution time ?

thewildotter

**Comment by LuPissarra** [comment]
inkStitch: like it for its simplicity
InkStitch: not really as the 'l' can be an 'small L' or a 'caps i' (even if I am a real fan of CamelCase)
INKStitch: an idea as INKSCAPE  uses only caps
INK---Stitch: I like the stitch idea

**Comment by lexelby** [comment]
Heya folks, welcome to the fold!

@thewildotter Wow, I love the idea of the moire patterns!  I can't wait to see what you come up with.  Please consider posting pictures so that we can see :)

I'm sorry to say that there's no "about" dialog as of yet.  It sounds to me like you at least have an old version of embroider.inx, if not the entire extension.  Perhaps you have an old installation of inkstitch in the system-wide `/usr/share/inkscape/extensions` that is overshadowing v1.3.1 in 1~/.config/inkscape/extensions`?  In any case, a full purge sounds like the way to go.

**Comment by thewildotter** [comment]
**Moire and More, Aye Cap'n**
@lexelby said, "I can't wait to see what you come up with."   So, first I did some plain long rectangles to see what Satin Column with each of the three underlay types would do.  You surely know what that would look like so I have not included them but the result was encouraging.  One original concern I had(and have) is that thread resolution(and the straight line segment construction of curves) may not do justice to two ovelaid spiral moire as I have achieved on plotters in the distant past.   I am very pleased to have discovered working parametric equations in inkscape so I decided to experiment with various spirals and resolutions.  I figured that I might have better luck in thread with curves which start more simply than those I did with plotters.   While I would like to use dimensional machine embroidery to the extent that I can, I would prefer starting with things that are likely to work in textiles early on.  That probably means I should use rulings rather than spirals but I love spirals so I decided to experiment with reducing the complexity of spirals to be used as the starting point for spiral designs.  Attached are some of my first experiments.  theNameofTheRose.png shows the lowest resolution one which can surely be implemented with nice satin column embroidery.  The spiralGalaxay.png can be used to challenge satin columns with various underlay options.  The inNbackOut.png will likely be quite challenging and may have to be implemented with technical tricks or perhaps just with running stitches.  The inNbackOut burger might be implemented with an "in" of one color on an opaque base cloth and a 
"backOut" on a second sheer cloth on top of a hollow spacer layer to get say 1/4" spacing between the two parts of the spiral.   The space will make the moire "kinetic" so that the interference pattern changes as one shifts one's observation angle.   Comments welcomed....

thewildotter

![thenameoftherose](https://user-images.githubusercontent.com/4745259/37174389-f18459b6-22db-11e8-8f47-54193fe0699f.png)
![spiralgalaxy](https://user-images.githubusercontent.com/4745259/37174413-07d0b8ea-22dc-11e8-8eab-4c16e3e41eec.png)
![innbackout](https://user-images.githubusercontent.com/4745259/37174452-24e149a4-22dc-11e8-81f6-b79f5ebfce2f.png)

**Comment by X3msnake** [comment]
@thewildotter @lexelby - don't take this the wrong way, but we should refrain from getting off topic. one can always open a new issue or post on the issue already open for drift talks called [forum](https://github.com/lexelby/inkstitch/issues/22). this issue is for voting on the brand name. ;)

Best regards.

**Comment by thewildotter** [comment]
No offence taken.  Never created a new issue before.  Is moire a good title ?  Can someone who knows how create it and move my last two posts ?  I don't want to mess it up.  

thewildotter

**Comment by X3msnake** [comment]
@thewildotter no worries Master it's easy, green button on the top

![image](https://user-images.githubusercontent.com/11083514/37180799-44521188-2322-11e8-9871-65551512f560.png)


Add title copy and paste the text

![image](https://user-images.githubusercontent.com/11083514/37180830-666f3f70-2322-11e8-8003-5542c487c5d2.png)

And click the submit button, presto ;)

then you can come back here and edit your post.

![image](https://user-images.githubusercontent.com/11083514/37180887-9eb2dd56-2322-11e8-8b38-831fb76df927.png)

delete the text and add a link to your new issue ;)

**Comment by lexelby** [comment]
Okay, at this point I think it's time to wrap up the voting, pick something, and go with it.  I hate to have to make a command decision without unanimous agreement, but at some point we just have to pick a color for the [bike-shed](https://en.wikipedia.org/wiki/Law_of_triviality) and stick with it. :)

We'll use these forms:

* Ink/Stitch
  * first letters capitalized
* INK/STITCH
  * acceptable for logos and similar where all-caps is part of the design
* inkstitch or InkStitch
  * use these for situations where slashes aren't allowed
  * capitalize the I and S if the situation allows, otherwise all lower case is fine

Notably, I'd like to avoid "inkStitch".  I just have an aversion to the i being lower-case and the S being capitalized.  Just looks wrong to me.

Thanks everyone for weighing in!

**Comment by X3msnake** [comment]
@lexelby :( 

inkStitch feels so natural to write.
Sorry but i must disagree with the color of the bike shed :)

why do you feel a aversion... aversion is good in the advertising industry you know?

**Comment by LuPissarra** [comment]
InkStitch: is the first letter a 'small L' or a 'caps i' ? ... not a great letter imho :(

inkStitch: so simple and understandable... :(

**Comment by X3msnake** [comment]
Your reference to the bike shed reminded me of another one that probably stems from your reference https://www.noisebridge.net/wiki/Do-ocracy

**Comment by slspencer** [comment]
InkStitch is easier to parse programmatically, also perhaps easier for
people to relate to. Plus, you can't pronounce slashes or dashes.
