### ISSUE TITLE
Satin Column Issue

### ISSUE THREAD

**Issue by wwderw** [lexelby/inkstitch#17]
Apparently, I'm unable to generate a satin column used Embroider.  If I want to generate any satin stitching, I go into XML editor and I change True to False for the Satin Column setting and then it generates.

I'm hoping that Satin Column allows for more editing of the shape (think turning satin stitching that I mentioned awhile back).  I however, am unable to use the "reshape tool" to make any changes to the overall shape of the satin stitch when I change that XML setting from True to False, it's static.

Also, how is the changes of the shape done with the node tool?  Is it at the individual stitch level or can it be broader then that?

After the column satin has gone through the reshape process, what would be the way of updating that info?  Is it already accounted for in the XML data or how exactly is it applied?
[Satin Test.zip](https://github.com/lexelby/inkstitch/files/1623904/Satin.Test.zip)

**Comment by lexelby** [comment]
This is almost entirely an issue with a lack of usability and documentation.  For starters, have you seen this? https://github.com/lexelby/inkstitch#satin-column

With Satin Columns, I'm kind of fighting against the lack of ability for my extension to control Inscape's UI directly.  To make a satin column, you'll need to create one path with two separate lines in it.  The extension will zig-zag between those paths -- even if they're not parallel.

You can optionally add lines to control the direction of the stitches at a specific spot, useful for maneuvering around a corner.  

Here's an example:
[lex_satin_example.zip](https://github.com/lexelby/inkstitch/files/1624151/lex_satin_example.zip)

> Also, how is the changes of the shape done with the node tool? Is it at the individual stitch level or can it be broader then that?

I think you're looking to try to manipulate the stitches in the Embroidery layer.  You'll find that you actually can't modify those stitch shapes at all, and that's by design.

The idea with ink/stitch is that you control _everything_ by manipulating the objects in inkscape, rather than individual stitches.  When you run Embroider, the primary purpose is to "render" the CSV file.  The stitch display you get in the Embroidery layer is only there for you to see what the output looks like.  I press undo immediately after I run Embroider and don't even bother keeping the Embroidery layer around.

I like to think of it as if the objects in Inkscape are a "program", and when you run Embroider you're "running the program".  It follows the instructions you've created (in the shapes and the settings you've added with Params), and produces a resulting stitch file with the fill stitch, satin, and running stitch that you've specified in your "program".

**Comment by wwderw** [comment]
The usual pathfinder tools (Union, Combine) to have two parallel lines into one path is giving me some hinky results.  Is there another method of combine the 2 lines that you used that the module will recognize?

**Comment by wwderw** [comment]
Hmmm, when I did straight on lines in parallel with combine option it seemed to work.  I'll try again with my more funky shapes when I get back from town, see if I can figure this thing out.  But at least I know it's the combine option for sure (or atleast that works for straight lines).

**Comment by wwderw** [comment]
Ok, I think given this shape, I had to do those bisecting lines for the stitch angle.  It couldn't render the shape without some help.  At least that solved it for this issue it seems.

That's pretty cool.  It reminds me what we had to do when we did hand embroidery and we drew on the fabric, we had to do the stitch angles like that.

**Comment by lexelby** [comment]
Union and Combine should both work fine.  Anything that produces a single Path object with two sub-paths in it will work fine.

The big pitfall, and perhaps what led to your hinky results, is that you need to make sure both sub-paths are going in the right direction.  If they're in opposite directions, then the stitches will all cross over in the center -- it'll be a big mess.  I have a demo of that in my <a href="https://www.youtube.com/watch?v=qXntE1X1RIw">video</a> around 3/4 of the way in.

I recommend you enable the feature in Preferences that adds little arrows to paths when you have the Node Editor tool selected, so you can see what direction they're going in.  To reverse just one sub-path, select at least one node in it, and do **Path -> Reverse** (ctrl+R).

> That's pretty cool. It reminds me what we had to do when we did hand embroidery and we drew on the fabric, we had to do the stitch angles like that.

Heh, glad you like it.  I can't tell if you're saying that ink/stitch's way of doing it is antiquated though? ;)

TBH, I'm not sure what the alternative is.  Would you expect the program to figure out how best to route the satin?  How would you adjust it if it gets it wrong?

**Comment by wwderw** [comment]
> The big pitfall, and perhaps what led to your hinky results, is that you need to make sure both sub-paths are going in the right direction. If they're in opposite directions, then the stitches will all cross over in the center -- it'll be a big mess.

I did get that, but I also got it in the simulated preview that it showed both as being stacked on top of one another.

It very well could have been going in the opposite direction, I didn't think of that.

> Heh, glad you like it. I can't tell if you're saying that ink/stitch's way of doing it is antiquated though? ;)

Not at all.  It gives me something familiar to help remember how to do things until I get used to using the extension.

> TBH, I'm not sure what the alternative is. Would you expect the program to figure out how best to route the satin? How would you adjust it if it gets it wrong?

As far as start to end point routing, this is actually the most logical way.  I couldn't think of an alternative with dealing with satin and run stitches.

**Comment by X3msnake** [comment]
Here's some info on how to fake a embroidery in Illustrator,

https://design.tutsplus.com/tutorials/create-an-embroidered-patch-style-with-adobe-illustrator--vector-5340

Maybe we can use the tips here to guide us on automating a preview effect on inkscape?
