### ISSUE TITLE
Print Error with 1.8.1

### ISSUE THREAD

**Issue by wwderw** [lexelby/inkstitch#174]
This is the error message that I got when I tried to do the "print" part of the extension on 1.8.1.

![print error](https://user-images.githubusercontent.com/24878362/40721192-67038106-63de-11e8-963e-3adf62b93c74.png)

This same file worked with the "print" extension in 1.8.0.

**Comment by lexelby** [comment]
Weird!  The error you're seeing is caused by an "invalid" shape, as defined by Shapely, the geometry library used by Ink/Stitch.  Am example of an "invalid" shape would be a figure 8, because the outer border crosses itself. I've had cases where the was a little tiny loop at a corner that I could only see if I zoomed in to line 2000%.  

Another example of an invalid shape would be a shape with a hole where the hole's border crosses the main shape's border or another hole's border.

Is it possible that your design has issues like the above?

The weird part is that it works in v1.8.1 but not v1.8.0.  Nothing I changed would have affected this part of the code...

If you can share the design with me, that'd really help, but I imagine that's difficult if this is for a customer. :)  If you want to email it to me directly, I'm at `inkstitch` at `lex` dot `gd`.

**Comment by wwderw** [comment]
Wouldn't that also affect the ability for Params to assign any embroidery values to it?

**Comment by lexelby** [comment]
Not exactly.  Params would be able to assign values, but the

**Comment by wwderw** [comment]
I figured it out. 

Going through the objects list, there were 3 rungs that didn't get combined into a satin object.  Combined them, make sure that Params still attached the values that I wanted, clicked applied and off we go.

**Comment by lexelby** [comment]
Cool!

Actually, could you open an issue for improving the user experience for "invalid" geometry?  Obviously there's nothing invalid about it from the user's perspective since inkscape let you do it!  Ink/Stitch should catch the error and give you tips on how to fix it.
