### ISSUE TITLE
Stitch Information

### ISSUE THREAD

**Issue by wwderw** [lexelby/inkstitch#19]
Would like to have the ability to see stitch info.

A couple of places that I think could show up, just depends on what's doable.  Ideally, it may not be bad to have all of them, but it does depend on what's doable.

1.  Within the XML editor itself.  Along with all the other individual embroidery parameters for each layer.  Here though, for us, it might be better to have just the last stitch number in the XML info.  That way we know that if we want to do 3 jump stitches in a row (which translates to a trim on most machines) we want to put it after this stitch number.

This would have to be able to live update if the stacking order changes.  At least in my mind, it should, thoughts on that?

2.  In the Simulate module, have the information displayed on the bottom of the player that shows progression (stitch x out of xx etc), play/pause, fast/slow etc

Something so that way we can get the actual stitch number of where we want to put in those individual commands.  This could also be done for any other commands that we would want to input at the individual stitch level, just so long as it's supported within the conversion program libembroidery-convert from the embroidermodder project.

**Comment by lexelby** [comment]
On the one hand, I see what you're getting at here.  On the other hand, I'd really rather provide you the ability to enter things like TRIM and STOP yourself through the UI.  Let's keep both possibilities in mind.

> This would have to be able to live update if the stacking order changes. At least in my mind, it should, thoughts on that?

That's one of those things that's just not possible for an extension to do in Inkscape.  Extensions can only do anything when the user runs them.  Inkscape pauses all of its activity, saves the SVG to a temporary file, and runs the extension program on that SVG.  The extension can modify the SVG as it sees fit, and then Inkscape loads it back.  That means live updating is unfortunately off the table. :(

Adding the stitch number to simulate should be pretty easy.  What's a little more tricky is the fact that there's no way to play a simulation backward! So you'd have to get close to the point you're looking for, then turn the speed _waaaaay_ down so that it advances one stitch at a time.  It'd be tedious.

Maybe we're looking at yet another possible feature, the ability to step backward as well as forward.  Given the way I've implemented Simulate right now, stepping backward is non-trivial, but it's definitely theoretically possible.

**Comment by wwderw** [comment]
> That's one of those things that's just not possible for an extension to do in Inkscape. Extensions can only do anything when the user runs them. Inkscape pauses all of its activity, saves the SVG to a temporary file, and runs the extension program on that SVG. The extension can modify the SVG as it sees fit, and then Inkscape loads it back. That means live updating is unfortunately off the table. :(

Update function in the extension that takes those objects that already have embroidery parameters in the XML and just press that button and it essentially recalculates and adjust that parameter accordingly?

>Adding the stitch number to simulate should be pretty easy. What's a little more tricky is the fact that there's no way to play a simulation backward! So you'd have to get close to the point you're looking for, then turn the speed waaaaay down so that it advances one stitch at a time. It'd be tedious.

If we can add the atleast the final stitch count to each object in the XML portion (for instance, if path 0123 ends at stitch count 867 (out of 5,000 stitches), then I know where to start doing my jump functions in the CSV file, if we can't handle that in the UI), I think that would eliminate the tediousness of scanning the simulator, but that would be best to have, if that information couldn't be added to the XML editor.

**Comment by lexelby** [comment]
@wwderw Do you still need this, now that we have TRIM and STOP options?

**Comment by wwderw** [comment]
Not in the 2 places originally mentioned since we have those trim and stop features.

Only place that I could see where the total design stitches would be very useful is in the PDF printout.  Otherwise, close this one on up.

**Comment by lexelby** [comment]
Yup, stitch count in the PDF printout sounds useful.  Perhaps the stitch number for each color change, too, since I saw that the machine also presents that information and it would be useful to be able to match them up.
