### ISSUE TITLE
Feature request : Makefile / cmake / setup.py

### ISSUE THREAD

**Issue by AkiraNorthstar** [lexelby/inkstitch#48]
Is there sometime a "real" makefile / setup.py / cmake filelist?
Given other distributions and operating systems, compile inkstitch natively would be great.
Most dependencies are required by Inkscape itself, for compiling you would have to install the development packages. I'm not a friend of static builds, so my question as an feature request.
I can build packages for RPM-based distributions, unfortunately I don't know enough about it in the "Python World". Is there a setup.py or a cmake template for Python modules/packages somewhere?

**Comment by AkiraNorthstar** [comment]
Question: If I have all the dependencies installed (WxPython and its dependency, wxGTK3,..., libembroidery with Python bindings), then I shouldn't need a inkstitch/bin directory anymore, right?
Or, in other ways, what is actually compiled?
```pip install -r requirements.txt```
builds WxPython, numpy and other packages (listed in requirements.txt).
Is there anything else compiled besides libembroidery?
I hope you understand what I mean...
It makes me confused

**Comment by wwderw** [comment]
I'm not to sure why you couldn't actually take the say V.1.1 that is in the Release section of this repo and put that in your extensions folder for Inkscape.  Even if using an RPM based distro versus a deb based distro.

Now, I'm not a coder/developer so I could be really far off and I haven't used an RPM distro since Fedora 22.

My eventual plan was when the dust settles and the features are in and it's stable is to bundle it with an AppImage of Inkscape, so in theory, I should be able to deploy that on any distro post 14.04 (that would include non Ubuntu distros, I'm just using the 14.04 as a time reference).

**Comment by AkiraNorthstar** [comment]
You are right. The tarball releases work fine. I prefer building packages by myself, when they are not in the distro repos, or in a outdated version. I like it modular - I'm a strange duck too! :)

**Comment by wwderw** [comment]
> I prefer building packages by myself, when they are not in the distro repos, or in a outdated version. I like it modular - I'm a strange duck too! :)

Hey, it's what keeps the world an interesting place.  I just wanted to make sure that I was thinking correctly.  Even after a few years of having Linux as a host with Windows guests, I know just enough to get into trouble.

So every now and again, I need to make sure my thinking is sound.

**Comment by lexelby** [comment]
@AkiraNorthstar You're right that there's nothing to build other than libembroidery.  The "build" that I have set up in `.travis.yml` uses pyinstaller which converts python code into an executable.  Actually it takes the compiled python bytecode and wraps it into an executable that runs it using libpython.  

pyinstaller also includes _all_ of the libraries used by the application down to (but not including) libc.  The idea is that anyone can grab the tarball, unpack it, and just _go_, without having to figuexecutablere out `pip install -r requirements.txt`, building wxpython, etc.  It pretty significantly reduces the barrier to entry.  People had a really hard time getting inkstitch working before I got the pyinstaller build in place.

Now, if you want to just run the extension "bare", you certainly executablecan!  I do.  I use [pyenv](https://github.com/pyenv/pyenv) so that I can do `pip install -r requirements.txt` as a normal user.  Then just build libembroidery.so and libembroidery.py, put them in your clone of inkstitch, and finally symlink all of the `embroider*.py` and `embroider*.inx` files into your inkscape extension dir, and you're good to go.  My `~/.config/inkscape/extensions` looks like this:

```
lrwxrwxrwx 1 lex lex     49 Dec 11 10:52 embroider.inx -> /home/lex/repos/inkscape-embroidery/embroider.inx
lrwxrwxrwx 1 lex lex     56 Dec 11 10:52 embroider_params.inx -> /home/lex/repos/inkscape-embroidery/embroider_params.inx
lrwxrwxrwx 1 lex lex     55 Dec 11 10:52 embroider_params.py -> /home/lex/repos/inkscape-embroidery/embroider_params.py
lrwxrwxrwx 1 lex lex     48 Dec 11 10:52 embroider.py -> /home/lex/repos/inkscape-embroidery/embroider.py
lrwxrwxrwx 1 lex lex     58 Dec 11 10:52 embroider_simulate.inx -> /home/lex/repos/inkscape-embroidery/embroider_simulate.inx
lrwxrwxrwx 1 lex lex     57 Dec 11 10:52 embroider_simulate.py -> /home/lex/repos/inkscape-embroidery/embroider_simulate.py
lrwxrwxrwx 1 lex lex     56 Dec 11 10:52 embroider_update.inx -> /home/lex/repos/inkscape-embroidery/embroider_update.inx
lrwxrwxrwx 1 lex lex     55 Dec 11 10:52 embroider_update.py -> /home/lex/repos/inkscape-embroidery/embroider_update.py
```

In any case, no, I don't think it's a good idea to set up the Makefile/cmake/setup.py.  You're welcome to add targets to the Makefile to suit your needs, such as one to build libembroidery and another to symlink the extension.  Just create a PR :)
